modLoader="javafml"
loaderVersion="[35,)"
license="Apache License 2.0"
[[mods]]
modId="lightmansdiscord"
version="${file.jarVersion}"
displayName="Lightmans Discord Integration"
logoFile="ldi.png"
#credits="Thanks for this example mod goes to Java"
authors="Lightman314"
description='''
Adds various Discord Integrations to your Minecraft Server!
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.lightmansdiscord]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightmansdiscord]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightmansdiscord]]
	modId="kotlinforforge"
	mandatory=true
	versionRange="[4.1.0,)"
	ordering="NONE"
	side="SERVER"